version: '3.7'
services:
  
  frontend:
    image: 277879185670.dkr.ecr.eu-west-1.amazonaws.com/tennis-front:latest
    environment:
      API_URL: ${API_URL}
    ports:
      - 80:80
    networks:
      - tennishub-net

  backend:
    image: 277879185670.dkr.ecr.eu-west-1.amazonaws.com/tennishub-api:latest
    deploy:
      x-aws-vpc: vpc-094409768029cdc18
    ports:
      - 8000:8000
    networks:
      - tennishub-net


networks:
  tennishub-net:
    driver: bridge
